Add implementation
apolo-actions/postgres pull request #1
Opened 2021-12-30 15:31 UTC by YevheniiSemendiak

@anayden, pls check if I haven't missed or mistyped something.
Thank you! <3

2021-12-30 16:56 UTC, anayden requested changes
LGTM overall, but feels like some small improvements are needed

2021-12-30 16:56 UTC, anayden commented on README.md
> +A work-around for this is to use a platform `disk:` to host the SQLite data.
I guess SQLite is a typo here :)

2021-12-30 16:56 UTC, anayden commented on README.md
> +### `http_auth`
How would one use http auth? As far as I know, Postgres doesn't provide web ui

2021-12-30 16:56 UTC, anayden commented on action.yaml
> +      Do not use the default value, instead consider Neu.ro secret: usage.
If we say "do not use default", let's remove the default.
Same for password

2021-12-30 16:56 UTC, anayden commented on action.yaml
> +      This optional environment variable can be used to send arguments to `postgres initdb`.
This is an argument, not environment variable

2022-01-04 11:11 UTC, YevheniiSemendiak commented on README.md
> +### `http_auth`
Hmm, googled it a bit, but you're right, HTTP API should be installed separately.
I've set it to true by default in 942d5b9 and removed it from the readme in 2c9dae0

2022-01-04 11:11 UTC, YevheniiSemendiak commented on action.yaml
> +      Do not use the default value, instead consider Neu.ro secret: usage.
completely agree! thank you for a good advice, applied in 2c9dae0

2022-01-04 11:16 UTC, YevheniiSemendiak commented on action.yaml
> +      This optional environment variable can be used to send arguments to `postgres initdb`.
correct, fixed in c84d841

2022-01-04 11:16 UTC, YevheniiSemendiak commented on README.md
> +A work-around for this is to use a platform `disk:` to host the SQLite data.
Yeah, thank you! c84d84196f85

2022-03-31 11:46 UTC, anayden approved these changes
Sorry, apparently I missed the PR in the past. All good!

2022-03-31 12:44 UTC, merged